[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = { version = "3.18.1", features = ["boxed", "collections"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
linked_list_allocator = "0.10.5"
spin = "0.10.0"
